### ISSUE TITLE
Modal date time picker not working in ios version 14.2 

### ISSUE THREAD

**Issue by donny08** [davecoffin/nativescript-modal-datetimepicker#76]
I am using nativescript 5.4.0

            
platform/ios "version": "6.5.2"

      And   "nativescript-modal-datetimepicker": "^1.1.12",

I have recently updated xcode version to 12.
I have attached screen shot of the issue if any one have the solution please assist.
![Screenshot 2020-11-15 at 10 11 47 PM](https://user-images.githubusercontent.com/9796105/99191632-a65f4480-278f-11eb-8f73-538bd08b4a7e.png)

**Comment by cwolff-wells** [comment]
It is fixed in version 1.2.4 with the commits from September 24th

**Comment by donny08** [comment]
@davecoffin

**Comment by donny08** [comment]
@cwolff-wells  After installing 1.2.4 version. I am getting below error on calling .pickDate() method

**Error: TypeError: application.systemAppearance is not a function. (In 'application.systemAppearance()', 'application.systemAppearance' is undefined)**

**Comment by tech-oss** [comment]
@shiv19 Can you please assist I am having the same issue when updated to 1.2.4 N below 7.

**Comment by tech-oss** [comment]
@shiv19  @cwolff-wells @davecoffin Error: TypeError: application.systemAppearance is not a function. (In 'application.systemAppearance()', 'application.systemAppearance' is undefined

**Comment by tech-oss** [comment]
@shiv19 @cwolff-wells @davecoffin Any one?

**Comment by cwolff-wells** [comment]
@tech-oss I have not run into that issue.  We are running Nativescript 6+.  The code for the ios date picker is at https://github.com/davecoffin/nativescript-modal-datetimepicker/blob/master/src/modal-datetimepicker.ios.ts.  It uses @nativescript/core which is Nativescript 6+.  If you don't want to start using @nativescript/core you may have to fork an older version that works for you and then add then add in those changes from September 24th.

**Comment by tech-oss** [comment]
@cwolff-wells I have updated the app to native script core using tns migrate command. And after that I updated all the plugins used.
But Its showing me an error please see complete log of terminal below:
roject successfully prepared (ios)
Configure firebase
Add iOS crash logging
Building project...
Xcode build...
error: Multiple commands produce '/Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework':
1) Target 'flowapp' (project 'flowapp') has copy command from '/Users/macbookpro/Documents/flow-app/node_modules/nativescript-ui-chart/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework' to '/Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework'
2) Target 'flowapp' (project 'flowapp') has copy command from '/Users/macbookpro/Documents/flow-app/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework' to '/Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework'
3) Target 'flowapp' (project 'flowapp') has copy command from '/Users/macbookpro/Documents/flow-app/node_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework' to '/Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework'

note: Using new build system
note: Planning build
note: Constructing build description
warning: duplicate output file '/Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework' on task: PBXCp /Users/macbookpro/Documents/flow-app/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework /Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework (in target 'flowapp' from project 'flowapp')
warning: duplicate output file '' on task: PBXCp /Users/macbookpro/Documents/flow-app/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework /Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework (in target 'flowapp' from project 'flowapp')
warning: duplicate output file '/Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework' on task: PBXCp /Users/macbookpro/Documents/flow-app/node_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework /Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework (in target 'flowapp' from project 'flowapp')
warning: duplicate output file '' on task: PBXCp /Users/macbookpro/Documents/flow-app/node_modules/nativescript-ui-listview/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework /Users/macbookpro/Documents/flow-app/platforms/ios/build/Debug-iphonesimulator/flowapp.app/Frameworks/TNSCore.framework (in target 'flowapp' from project 'flowapp')
** BUILD FAILED **

Unable to apply changes on device: 4D8959B3-257F-4272-9C0C-D34F4E5C4D82. Error is: Command xcodebuild failed with exit code 65.

**Comment by tech-oss** [comment]
@cwolff-wells I am using xcode version 11.2 & here is my package.json file:
{
    "nativescript": {
        "id": "com.atrixdigital.flow",
        "tns-android": {
            "version": "6.0.0"
        },
        "tns-ios": {
            "version": "6.2.0"
        }
    },
    "scripts": {
        "build-ios": "tns build ios --bundle --env.uglify && tns prepare ios --release",
        "build-android": "tns build android --bundle --env.uglify --release --keyStorePath atflow.jks --keyStorePassword 122Elgin18! --keyStoreAlias flowAlias --keyStoreAliasPassword 122Elgin18!"
    },
    "description": "NativeScript Application",
    "license": "SEE LICENSE IN <your-license-filename>",
    "repository": "<fill-your-repository-here>",
    "dependencies": {
        "@angular/animations": "8.0.0",
        "@angular/common": "8.0.0",
        "@angular/compiler": "8.0.0",
        "@angular/core": "8.0.0",
        "@angular/forms": "8.0.0",
        "@angular/http": "8.0.0-beta.10",
        "@angular/platform-browser": "8.0.0",
        "@angular/platform-browser-dynamic": "8.0.0",
        "@angular/router": "8.0.0",
        "moment": "^2.24.0",
        "nativescript-angular": "^10.0.0",
        "nativescript-appversion": "^1.4.4",
        "nativescript-bottom-navigation": "^2.0.5",
        "nativescript-camera": "^4.5.0",
        "nativescript-checkbox": "^3.0.3",
        "nativescript-datetimepicker": "^1.2.3",
        "nativescript-directions": "^1.4.0",
        "nativescript-filterable-listpicker": "^2.2.6",
        "nativescript-floatingactionbutton": "^5.1.0",
        "nativescript-fontawesome": "^1.0.0",
        "nativescript-gradient": "^2.0.1",
        "nativescript-iqkeyboardmanager": "^1.5.1",
        "nativescript-loading-indicator": "^2.5.2",
        "nativescript-localstorage": "^2.0.1",
        "nativescript-modal-datetimepicker": "^2.1.2",
        "nativescript-phone": "^2.0.0",
        "nativescript-plugin-firebase": "^10.6.3",
        "nativescript-socketio": "^3.3.1",
        "nativescript-theme-core": "^2.0.24",
        "nativescript-toasty": "^3.0.0-alpha.2",
        "nativescript-ui-chart": "^8.0.2",
        "nativescript-ui-listview": "^9.0.4",
        "nativescript-ui-sidedrawer": "^9.0.3",
        "reflect-metadata": "~0.1.8",
        "rxjs": "^6.3.3",
        "rxjs-compat": "^6.3.3",
        "tns-core-modules": "^6.5.21",
        "zone.js": "0.9.1"
    },
    "devDependencies": {
        "@angular/compiler-cli": "8.0.0",
        "@nativescript/schematics": "~0.5.0",
        "@ngtools/webpack": "8.0.0",
        "nativescript-dev-webpack": "^1.5.1",
        "tns-platform-declarations": "^6.5.1",
        "typescript": "3.4.5"
    },
    "gitHead": "9b6565a4513375a33a59c44262dfc1d818a8205e",
    "readme": "NativeScript Application"
}
